apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://crowdsecurity.github.io/helm-charts
    chart: crowdsec
    targetRevision: "0.23.0"
    helm:
      valuesObject:
        commonLabels:
          app: crowdsec
          team: platform
          env: production
        agent:
          podLabels:
            app: crowdsec
            team: platform
            env: production
          metrics:
            serviceMonitor:
              enabled: true
          acquisition:
            - namespace: traefik
              podName: traefik-*
              program: traefik
          env:
            - name: COLLECTIONS
              value: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios"
        lapi:
          podLabels:
            app: crowdsec
            team: platform
            env: production
          dashboard:
            enabled: false
          metrics:
            serviceMonitor:
              enabled: true
          extraVolumes:
            - name: console-credentials
              secret:
                secretName: crowdsec-online-api-credentials
          extraVolumeMounts:
            - name: console-credentials
              mountPath: /etc/crowdsec/online_api_credentials.yaml
              subPath: online_api_credentials.yaml
              readOnly: true
          persistentVolume:
            config:
              enabled: true
              storageClassName: ceph-block
              size: 1Gi
            data:
              enabled: true
              storageClassName: ceph-block
              size: 2Gi
          env:
            - name: BOUNCER_KEY_traefik
              valueFrom:
                secretKeyRef:
                  name: crowdsec-bouncer-key
                  key: key
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
