apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: display-manager-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
