apiVersion: v1
kind: Service
metadata:
  name: display-manager
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: display-manager
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
