apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: {{ .Values.namespace }}
  labels:
    app: uptime-kuma
    team: platform
    env: {{ .Values.env }}
spec:
  type: ClusterIP
  selector:
    app: uptime-kuma
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
