apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-schedules
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/joyson-fernandes/storage.git
    targetRevision: HEAD
    path: manifests/velero-schedules
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
