namespace: display-manager
env: production

image:
  repository: registry.joysontech.com/library/display-manager
  tag: "d011572"
  pullPolicy: Always

port: 8092

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
