apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/joyson-fernandes/platform.git
    targetRevision: main
    path: developer-ui/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
