apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phpipam-db
  namespace: {{ .Values.namespace }}
  labels:
    app: phpipam
    team: platform
    env: {{ .Values.env }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: phpipam-db
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: {{ .Values.vault.path }}
        property: root-password
    - secretKey: user-password
      remoteRef:
        key: {{ .Values.vault.path }}
        property: user-password
