apiVersion: v1
kind: Service
metadata:
  name: phpipam-web
  namespace: {{ .Values.namespace }}
  labels:
    app: phpipam
    tier: app
    team: platform
    env: {{ .Values.env }}
spec:
  type: ClusterIP
  selector:
    app: phpipam
    tier: app
  ports:
    - port: 80
      targetPort: http
      name: http
