apiVersion: apps/v1
kind: Deployment
metadata:
  name: apcd
  namespace: {{ .Values.namespace }}
  labels:
    app: apcd
    team: platform
    env: {{ .Values.env }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: apcd
  template:
    metadata:
      labels:
        app: apcd
        team: platform
        env: {{ .Values.env }}
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: apcd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LISTEN_ADDR
              value: ":{{ .Values.port }}"
          ports:
            - containerPort: {{ .Values.port }}
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            initialDelaySeconds: 2
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
