apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apcd-joysontech-com
  namespace: {{ .Values.namespace }}
spec:
  secretName: apcd-joysontech-com-tls
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.host }}
  duration: 8760h
  renewBefore: 720h
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: apcd
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.host }}`)
      middlewares:
        - name: local-only
          namespace: traefik
      services:
        - name: apcd
          port: {{ .Values.port }}
  tls:
    secretName: apcd-joysontech-com-tls
