apiVersion: v1
kind: Service
metadata:
  name: apcd
  namespace: {{ .Values.namespace }}
  labels:
    app: apcd
    team: platform
    env: {{ .Values.env }}
  annotations:
    metallb.io/loadBalancerIPs: {{ .Values.loadBalancerIP | quote }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  selector:
    app: apcd
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
