apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.18.3"
      helm:
        valueFiles:
          - $values/helm/values.yaml
    - repoURL: https://github.com/joyson-fernandes/harbor.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
