apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
  namespace: {{ .Values.namespace }}
  labels:
    app: cloudflared
    team: platform
    env: {{ .Values.env }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflared-tunnel
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.vault.path }}
        property: {{ .Values.vault.key }}
