namespace: phpipam
env: production
timezone: Europe/London
host: ipam.joysontech.com

web:
  image:
    repository: phpipam/phpipam-www
    tag: "v1.7.4"
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

cron:
  image:
    repository: phpipam/phpipam-cron
    tag: "v1.7.4"
    pullPolicy: IfNotPresent
  scanInterval: "1h"
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

mariadb:
  image:
    repository: mariadb
    tag: "11.4"
    pullPolicy: IfNotPresent
  database: phpipam
  user: phpipam
  storage:
    storageClass: ceph-block
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

vault:
  path: phpipam/db
